# Generated by Django 5.2.7 on 2025-10-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'permissions': [('can_block_users', 'Может блокировать пользователей'), ('can_disable_mailings', 'Может отключать рассылки')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
