# Generated by Django 5.2.7 on 2025-10-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['-attempt_time'], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылок'},
        ),
    ]
