# Generated by Django 5.2.7 on 2025-10-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingattempt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала отправки'),
        ),
    ]
